### ISSUE TITLE
Circular dependency from 0dc8d8d

### ISSUE THREAD

**Issue by rapilabs** [douglasmiranda/django-wysiwyg-redactor#139]
Commit 0dc8d8d6fa91abf7506cb8f6d74a29ece8475a68 has created a circular dependency in my project, due to the relocation of `json_dumps()` to a constructor.

Using Django 1.10, Python 3.5.2.

Please consider reverting this commit, opening a new PR/branch and asking the author to test.

Below is the full (and redacted) traceback where you can see `models.py` is imported twice:

```
$ ./manage.py
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/redacted/project/path/backend/env/lib/python3.5/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/redacted/project/path/backend/env/lib/python3.5/site-packages/django/core/management/__init__.py", line 341, in execute
    django.setup()
  File "/redacted/project/path/backend/env/lib/python3.5/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/redacted/project/path/backend/env/lib/python3.5/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/redacted/project/path/backend/env/lib/python3.5/site-packages/django/apps/config.py", line 199, in import_models
    self.models_module = import_module(models_module_name)
  File "/redacted/project/path/backend/env/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/redacted/project/path/backend/apps/content/models.py", line 45, in <module>
    class Page(models.Model):
  File "/redacted/project/path/backend/apps/content/models.py", line 51, in Page
    content = RedactorField(blank=True, allow_file_upload=True, allow_image_upload=True, redactor_options={'replaceDivs': False}, help_text=REDACTOR_HELP)
  File "/redacted/project/path/backend/env/lib/python3.5/site-packages/redactor/fields.py", line 17, in __init__
    allow_image_upload=allow_image_upload
  File "/redacted/project/path/backend/env/lib/python3.5/site-packages/redactor/widgets.py", line 21, in __init__
    'data-redactor-options': json_dumps(self.options)}
  File "/redacted/project/path/backend/env/lib/python3.5/site-packages/redactor/utils.py", line 55, in json_dumps
    return json.dumps(data, cls=LazyEncoder)
  File "/usr/local/Cellar/python3/3.5.2_1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/__init__.py", line 237, in dumps
    **kw).encode(obj)
  File "/usr/local/Cellar/python3/3.5.2_1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/encoder.py", line 198, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/Cellar/python3/3.5.2_1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/encoder.py", line 256, in iterencode
    return _iterencode(o, 0)
  File "/redacted/project/path/backend/env/lib/python3.5/site-packages/redactor/utils.py", line 50, in default
    return force_text(obj)
  File "/redacted/project/path/backend/env/lib/python3.5/site-packages/django/utils/encoding.py", line 76, in force_text
    s = six.text_type(s)
  File "/redacted/project/path/backend/env/lib/python3.5/site-packages/django/utils/functional.py", line 116, in __text_cast
    return func(*self.__args, **self.__kw)
  File "/redacted/project/path/backend/env/lib/python3.5/site-packages/django/urls/base.py", line 91, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "/redacted/project/path/backend/env/lib/python3.5/site-packages/django/urls/resolvers.py", line 341, in _reverse_with_prefix
    self._populate()
  File "/redacted/project/path/backend/env/lib/python3.5/site-packages/django/urls/resolvers.py", line 193, in _populate
    for pattern in reversed(self.url_patterns):
  File "/redacted/project/path/backend/env/lib/python3.5/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/redacted/project/path/backend/env/lib/python3.5/site-packages/django/urls/resolvers.py", line 310, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/redacted/project/path/backend/env/lib/python3.5/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/redacted/project/path/backend/env/lib/python3.5/site-packages/django/urls/resolvers.py", line 303, in urlconf_module
    return import_module(self.urlconf_name)
  File "/redacted/project/path/backend/env/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/redacted/project/path/backend/redacted-project-name/urls.py", line 6, in <module>
    from apps.content.views import PageViewSet
  File "/redacted/project/path/backend/apps/content/views.py", line 4, in <module>
    from .serializers import PageSerializer
  File "/redacted/project/path/backend/apps/content/serializers.py", line 6, in <module>
    class PageSerializer(serializers.ModelSerializer):
  File "/redacted/project/path/backend/apps/content/serializers.py", line 9, in PageSerializer
    class Meta:
  File "/redacted/project/path/backend/apps/content/serializers.py", line 10, in Meta
    model = models.Page
AttributeError: module 'apps.content.models' has no attribute 'Page'
```

**Comment by gastlich** [comment]
@rapilabs I don't know if this is related or not, but Django 1.10 stopped supporting: django.conf.urls.patterns(), so current version of django-wysiwig-editor is not supported by Django 1.10. Recently PR #134 was merged, which will make this repo compatible with 1.10, but a release hasn't been done yet.

```
RemovedInDjango110Warning: django.conf.urls.patterns() is deprecated and will be removed in Django 1.10. Update your urlpatterns to be a list of django.conf.urls.url() instances instead.
```

**Comment by rapilabs** [comment]
@gastlich not related ;)
